//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planner2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public int CategoryRowID { get; set; }
        public string CategoryName { get; set; }
        public string Description { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string SeoUrl { get; set; }
        public string Menu { get; set; }
        public Nullable<int> STT { get; set; }
        public Nullable<double> Price7Day { get; set; }
        public Nullable<double> Price15Day { get; set; }
        public Nullable<double> Price30Day { get; set; }
        public Nullable<double> Price2Month { get; set; }
        public Nullable<double> Price3Month { get; set; }
        public Nullable<double> Price6Month { get; set; }
        public Nullable<double> Price1Year { get; set; }
        public Nullable<double> Price2Year { get; set; }
        public Nullable<double> Price5Year { get; set; }
    }
}
