//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planner2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataViewer
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string QueryData { get; set; }
        public int Show { get; set; }
        public string TYPE { get; set; }
        public int Editor { get; set; }
        public string TableEdit { get; set; }
        public string UserView { get; set; }
    }
}
