//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planner2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int ID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public string StaffID { get; set; }
        public Nullable<System.DateTime> DATECREATE { get; set; }
        public string NOIDUNG { get; set; }
        public Nullable<int> Type { get; set; }
    }
}
