//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planner2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainTask
    {
        public int Id { get; set; }
        public string TaskName { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public string AttendPerson { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<double> DienTich { get; set; }
        public Nullable<double> Gia { get; set; }
        public string TyGia { get; set; }
        public Nullable<int> KhuVuc_TP { get; set; }
        public Nullable<int> KhuVuc_Huyen { get; set; }
        public Nullable<int> KhuVuc_Xa { get; set; }
        public string Map_DiaDiem { get; set; }
        public string Map_LoaiBatDongSan { get; set; }
        public string Map_Huong { get; set; }
        public Nullable<int> Map_SoPhongNgu { get; set; }
        public string Map_DuAn { get; set; }
        public string Map_TenLienLac { get; set; }
        public string Map_DienThoai { get; set; }
        public string Map_Zalo { get; set; }
        public string Map_Skyper { get; set; }
        public string Map_Email { get; set; }
        public string Tag { get; set; }
        public Nullable<bool> Publish { get; set; }
        public string SeoUrl { get; set; }
        public Nullable<bool> Comment { get; set; }
        public string Picture { get; set; }
        public Nullable<int> Viewer { get; set; }
        public Nullable<bool> Page { get; set; }
        public int UuTien { get; set; }
        public string Youtube { get; set; }
        public string CategoryList { get; set; }
        public string TinMuaBan { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
    }
}
