//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planner2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhPho
    {
        public string TenThanhPho { get; set; }
        public int MaThanhPho { get; set; }
        public string QuanHuyen { get; set; }
        public int MaQuanHuyen { get; set; }
        public string PhuongXa { get; set; }
        public int MaPhuongXa { get; set; }
        public string Cap { get; set; }
    }
}
