//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planner2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadFile
    {
        public int ID { get; set; }
        public string FileName { get; set; }
        public string UrlFile { get; set; }
        public string TableName { get; set; }
        public string ColumnName { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string Note { get; set; }
        public Nullable<int> TaskID { get; set; }
    }
}
