//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planner2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string StaffName { get; set; }
        public string StaffID { get; set; }
        public string NgDuyet { get; set; }
        public string Dept { get; set; }
        public string UserName { get; set; }
        public Nullable<int> SupperAdmin { get; set; }
        public string Parts { get; set; }
        public string Password { get; set; }
        public string Active { get; set; }
        public Nullable<int> SoTien { get; set; }
        public string SDT { get; set; }
        public string DiaChi { get; set; }
        public string AvartaImg { get; set; }
    }
}
